### ISSUE TITLE
Problemas acceder a Settings

### ISSUE THREAD

**Issue by estebandidoreg** [micro-joan/BlackStone#12]
Hola, 

Descargando la versión de 18-10 no permite ingresar a "seetings"  http://localhost/BlackStone/editar_perfil.php  indicando: The value entered is not correct.

Favor su ayuda y gracias por el apoyo a la comunidad.

**Comment by micro-joan** [comment]
Ya está solucionado, puedes volver a descargar la herramienta o sustituir de este repo el archivo "editar_perfil.php" en la ruta "/opt/lampp/htdocs/BlackStone".
