### ISSUE TITLE
Kali error

### ISSUE THREAD

**Issue by Milodcz** [micro-joan/BlackStone#6]
Hola, he seguido los pasos que indicas, pero al parecer no instala el Xammp en mi Kali y no se porque, al abrirse el navegador, me dice que no hay conexion con el localhost.
punto 2. lo hice como root, no se si estara bien.
punto 3, he notado que cuando hago el clone, luego de instalar la primera vez, no me deja entrar a la carpéta Blackstone en opt, me dice que no existe o que no es una carpeta, pero cuando abro el mc, puedo entrar y hasta ejecutar nuevamente el installer.

Saludos!

**Comment by WannaCr** [comment]
Me paso lo mismo, lo solucione de la siguiente manera:

cd /op/blackstone (Esta es la ubicacion donde se guarda el instalador XAMMP)
cp -r xampp_installer /opt/BlackStone (Para copiarlo en la ruta donde esta el instalador)

chmod +x installer.sh
./installer.sh

**Comment by micro-joan** [comment]
Many installation errors have been patched since the last update. I recommend downloading BlackStone again and performing a new installation. I also leave you my YouTube video where I explain the installation step by step. ¡¡All the best!!

https://youtu.be/3Z0lts176sE
