### ISSUE TITLE
No renderiza las imagenes

### ISSUE THREAD

**Issue by G4sp4rCS** [micro-joan/BlackStone#9]
Hola! te quería comentar que a la hora de attachear no renderiza las imagenes, y no estoy seguro si es porque falta alguna especie de libreria que tome attachments desde fuera del localhost hacia el servidor, pues yo levanto la app desde el docker y attacho las imagenes desde mi sistema operativo host que es windows 10.

**Comment by micro-joan** [comment]
Debes guardar el documento .mhtml en formato word mientras BlackSone siga
encendido, de manera que al guardarlo en .doc las imágenes se guardan en el
documento y no se renderizan desde la aplicación, si tienes el documento en
format .mhtml y cierras BlacKstone desaparecerán, dado que dichas imágenes
apuntan al directorio de la aplicación.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by micro-joan** [comment]
Entonces es tema de permisos, debes otorgar permisos al directorio entero
en el que se encuentra BlackStone y solucionado!
